### ISSUE TITLE
Current instance not loading route overlay in macOS

### ISSUE THREAD

**Issue by Skippern** [plepe/ptmap#5]
Current instance is not loading the route overlay in any of my browsers (tried Safari, Chrome, and Firefox). All browsers are on latest stable release. OS X El Capitan 10.11.6.

Background tiles loads ok, but the route information (overpass query?) doesn't load or process. Indicator keep indicating that the map is loading. Reload doesn't help. Waiting doesn't help.

Tested here: https://ptmap.plepe.at/#lat=-20.66922&lon=-40.49878&zoom=18

**Comment by plepe** [comment]
That was a tricky one. I finally had time to dig into the problem.

The output format of the Overpass API was changed slighlty (in particular the result of the 'out count' statement) and that's why it was no longer working.

My testing environment used a different Overpass server with an older version and therefore was not affected.

-> Fixed. (plepe/overpass-frontend@6e2f0d3028e42ed906fc5ebc801ed342be18b41f)

(Don't forget to press Reload)
